//create
export const CREATE_BRAND_REQUEST = 'CREATE_BRAND_REQUEST'
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS'
export const CREATE_BRAND_FAIL = 'CREATE_BRAND_FAIL'
export const CREATE_BRAND_RESET = "CREATE_BRAND_RESET"

//all
export const ALL_BRAND_REQUEST = 'ALL_BRAND_REQUEST'
export const ALL_BRAND_SUCCESS = 'ALL_BRAND_SUCCESS'
export const ALL_BRAND_FAIL = 'ALL_BRAND_FAIL'

//single
export const SINGLE_BRAND_REQUEST = 'SINGLE_BRAND_REQUEST'
export const SINGLE_BRAND_SUCCESS = 'SINGLE_BRAND_SUCCESS'
export const SINGLE_BRAND_FAIL = 'SINGLE_BRAND_FAIL'

//update
export const UPDATE_BRAND_REQUEST = "UPDATE_BRAND_REQUEST"
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS"
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_SUCCESS"
export const UPDATE_BRAND_RESET = "UPDATE_BRAND_RESET"

//delete
export const DELETE_BRAND_REQUEST = 'DELETE_BRAND_REQUEST'
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS'
export const DELETE_BRAND_RESET = 'DELETE_BRAND_RESET'
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL'

//clear error
export const CLEAR_ERRORS = "CLEAR_ERRORS"